spring:
  datasource:
    url: jdbc:mysql://yjo6uubt3u5c16az.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/euuq2kmf6akoioay
    username: upfp26j1httg7gww
    password: lwm0n1t6o2piop6s
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
server:
  servlet:
    context-path: /api/v1
  port: 8081